limit_req_zone $binary_remote_addr zone=perip:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=payments:10m rate=2r/s;
limit_conn_zone $binary_remote_addr zone=addrconn:10m;
client_body_timeout 12s;
client_header_timeout 12s;
send_timeout 10s;
